DATA:
  LAST_TRANSFORM: false
  NUM_PATCHES: 12
  IS_IP: false
  PATCH_SIZE: [300,300]
  STRIDE: [300,300]
  DROP_LAST: false
  
TRAINER:
  NAME: ioplin

IOPLIN:
  UPDATE_FREQ: 2
  R_THR_RATIO: 0.55
  MIN_SAMPLE_WEIGHT: 0.1