AUG:
  NORM: [[0.5,0.5,0.5],[0.5,0.5,0.5]]
  NO_AUG: false

DATA:
  DATALOADER_NAME: torch_img_pict
  IMG_SIZE: [300,300]
  BATCH_SIZE: 12
  CLS_NOR_INDEX: 0
  CLASS_MAP: [normal,diseased]

TRAINER:
  NAME: wsplin

TEST:
  BINARY_MODE: false
  
MODEL:
  RESUME: 97.2_effi_b3_bin_backbone.pth
  NAME: tf_efficientnet_b3
  NUM_CLASSES: 2

TRAIN_MODE: eval
