DATA:
  DATALOADER_NAME: torch_img_pict
  IMG_SIZE: (224,224) #(384,384)
  BATCH_SIZE: 32
  VAL_BATCH_SIZE: 128
MODEL: 
  NUM_CLASSES: 8      
  # swin_base_patch4_window12_384_in22k  pvt_medium pvt_v2_b3
  NAME: swin_small_patch4_window7_224
  DROP_PATH_RATE: .3
  DROP_RATE: .0
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 2
  MIN_LR : 5.0e-7          # 这是swin的参数， 5e-6，5e-7。config文件里是cub的参数，swinpim那个文章给的
  WARMUP_LR: 5.0e-7
  LR_BS_SCALE: 32
  OPTIMIZER:
      EPS:  1.0e-8
  BASE_LR: 1.0e-4
AUG:
  MULTI_VIEW: None
  NO_AUG: true
TEST:
  CROP: 0.
  BEST_MODEL_METRIC: ['main','macro_f1']
  
# THUMB_MODE: true
MODEL_EMA: false
#LOG_WANDB: true
#BINARYTRAIN_MODE: true
TRAINER:
  NAME: iNet_cls
